name: t_store
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.6.0



dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  http: ^1.3.0
  intl: ^0.17.0
  logger: ^2.5.0
  url_launcher: ^6.0.9
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0

  #STATE MANAGEMENT
  get: ^4.3.8
  get_storage: ^2.0.3

  #Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  
  
  #Firebase
  firebase_core: ^3.13.0
  lottie: ^3.0.0
  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:

 
  uses-material-design: true
  assets:
    - assets/images/on_boarding_images/  
    - assets/icons/
    - assets/icons/categories/
    - assets/logos/
    - assets/images/
    - assets/images/animation/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/ratings/
    - assets/icons/payment_methods/
    - assets/images/user/


    - assets/icons/categories/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-SemiBold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-ExtraLight.ttf
        - asset: assets/fonts/Roboto-Thin.ttf  

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
